### ISSUE TITLE
How many states for MultiTypeTree at most?

### ISSUE THREAD

**Issue by lixingguang** [tgvaughan/MultiTypeTree#15]
@tgvaughan How many states for MultiTypeTree at most? 4 ? Thanks.

**Comment by tgvaughan** [comment]
There's no limit in principle, although 4-5 seems to be the practical limit without additional constraints on the migration matrix.  (Informative priors can help a lot here.  If the number of degrees of freedom in the migration matrix and Ne vectors can be kept low, you can include many more demes.)
