### ISSUE TITLE
Bayes Factor in SpreaD3

### ISSUE THREAD

**Issue by amymariecampbell** [tgvaughan/MultiTypeTree#22]
Is it possible to obtain Bayes Factor for MultiTypeTree structured coalescent models in SpreaD3? (https://rega.kuleuven.be/cev/ecv/software/SpreaD3_tutorial#sectionFourTwo)

It seems this relies on a rateIndicator column in the log file but I can't see this in my MultiTypeTree log file. I'd like some way to compare the likelihood of my models to find those with most statistical support for the locations. 

Thanks so much in advance.

**Comment by tgvaughan** [comment]
Hi @amymariecampbell, I don't know anything about SpreaD3, but no this isn't directly possible.  The phylogeography method mentioned in the document that you referenced uses a state space augmentation technique, "BSSVS", to turn individual rates matrix elements on and off during the analysis.  MultiTypeTree doesn't generally work this way - at least "out of the box", so would require a bit of technical work to set this up, for instance by using [ModelSelectionParameter](https://github.com/tgvaughan/feast#model-selection-using-modelselectionparameter) to sample the presence/absence of different transition rates.

Cheers,
Tim

**Comment by amymariecampbell** [comment]
Hi Tim,

OK, thank you for your rapid response! Is there a more intuitive way to compare model performance (in terms of the allocated types/locations) of MultiTypeTree models?

Thanks,

Amy
________________________________

**Comment by liamxg** [comment]
@tgvaughan how to do that using Modelselectionparameter, and tutorials on this ?

**Comment by tgvaughan** [comment]
@LiXingguangBrandonStark The documentation I linked above is all I've written on that, but if you're familiar with BSSVS and BEAST XML you should be able to put something together.  The BEAST 2 documentation is a good place to start getting to grips with the XML format, while Phillipe Lemey's phylogeography paper (https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000520) is a good point to start learning about BSSVS.

@amymariecampbell The posterior distribution yields marginal posteriors for each of the internal node locations.  These can be directly computed using TreeAnnotator to generate a summary tree and can be explored by loading that tree into FigTree.  The relevant tutorials on taming-the-beast.org give details on how to do this.

**Comment by liamxg** [comment]
@tgvaughan thanks, i am not familiar with xml, and I do not find multitypetree in beast 2.7.1?
<img width="907" alt="image" src="https://user-images.githubusercontent.com/46078579/195980631-ece92c8a-f7b3-4ec9-95ad-319c8e2e35a9.png">

**Comment by tgvaughan** [comment]
MultiTypeTree is not compatible with BEAST 2.7.  You'll have to use BEAST 2.6.

**Comment by liamxg** [comment]
@tgvaughan, thanks. When will it compatible with 2.7?

**Comment by tgvaughan** [comment]
@LiXingguangBrandonStark when I get a chance to update it.  2.7 is a major update, and supporting it means I'll have to rewrite MultiTypeTree's BEAUti code, which is not straight-forward.  Hopefully this will be possible by the end of this year.  (I have many other packages which require similar rewrites, so together it's a fair amount of work.)

**Comment by liamxg** [comment]
@tgvaughan thanks for your great work.

**Comment by amymariecampbell** [comment]
@tgvaughan 
Hi Tim, thanks for your reply. The summary trees are what is making me question which model of mine is strongest.
I'm interested in when and where the variant I am looking at originated.  It seems slightly different parameters or MCMC runs seem to provide a similar tree structure (an initial split into two clear groups), however the type allocation to the root and the the branches splitting into these two groups are completely different for each run. I have three demes (locations) and I've had the root and the two groups attributed to each of these 3 with high 'type' probability (>0.9) posterior support. So I'm trying to work out if there are any robust results here, and why it seems to confidently allocate the branches to one deme, but then a slight change in parameters completely changes this to highly support another deme. And trying to work out which of these estimates has the most support. Does that make sense?
